from typing import Literal

from pydantic import BaseModel, Field, field_validator

EvidenceType = Literal[
    "skills_only", "project_mention", "experience_mention", "demonstrated_usage", "external_verification"
]

UrlKind = Literal["github_profile", "github_repo", "linkedin", "kaggle", "portfolio"]


class ExtractedUrl(BaseModel):
    url: str
    kind: UrlKind

# =======================
# LLM structured-output schemas (used as Groq tool-call parameters)
# =======================


class WeightedSkill(BaseModel):
    # Named `name`, not `skill` -- openai/gpt-oss-20b (see config.py) reliably
    # emitted "name" as the key for each list item regardless of what this
    # field was actually called, which Groq's own schema validation then
    # rejected outright (tool_use_failed) on every single call. Matching the
    # model's natural naming fixed it 5/5 in testing; renaming the schema
    # field is a real fix, unlike prompting it not to.
    name: str = Field(description="Lowercase skill name")
    weight: float = Field(
        ge=0.0, le=1.0, description="Importance for the role: 0=least, 1=most important"
    )


class WeightedSkillList(BaseModel):
    skills: list[WeightedSkill] = Field(default_factory=list)


class RequirementVerdictCore(BaseModel):
    """The batch-scoring schema -- deliberately has NO certification field.

    Certifications used to be requested in the same call as the
    satisfied/evidence verdict. Under batching, the model started
    cross-attributing output between semantically similar requirements in
    the same call (citing one skill's evidence for another, or attaching an
    unrelated certification). Structurally excluding the field here -- not
    just prompting the model not to fill it -- makes it impossible for a
    batch call to emit one at all; certifications are generated by a
    separate, later call (see `CertificationSuggestionList`) scoped to only
    the unsatisfied requirements.
    """

    requirement: str = Field(description="The exact JD requirement/skill text this verdict is for")
    weight: float = Field(ge=0.0, le=1.0)
    satisfied: bool = Field(description="True only if the provided evidence actually demonstrates this")
    evidence_type: EvidenceType | None = Field(
        default=None,
        description=(
            "Only when satisfied=true -- how strongly the cited evidence demonstrates this "
            "requirement. 'skills_only': the only evidence is a bare mention inside a "
            "skills/technologies list, no sentence showing it being used. 'project_mention' / "
            "'experience_mention': mentioned within a project or work-experience bullet, but "
            "without a clear specific action or outcome tied to it. 'demonstrated_usage': "
            "evidence shows the skill actively being used to build, do, or achieve something "
            "concrete. Null when satisfied=false."
        ),
    )
    # Deterministic, not LLM-supplied: computed from evidence_type via
    # settings.evidence_type_weights right after the model's verdicts come
    # back (see _evaluate_rubric_batch) -- not requested from the model, an
    # LLM asked to self-report a calibrated 0-1 confidence isn't reliable at
    # it (a bare skills-list mention scored a flat 1.0 in testing).
    confidence: float = Field(default=0.0, ge=0.0, le=1.0)
    # Set only by the external-evidence corroboration step (see
    # external_evidence.py), never by the resume-only rubric call -- the URL
    # of the GitHub repo/profile that corroborated or satisfied this
    # requirement, so the UI can cite exactly where it came from.
    external_source_url: str | None = Field(default=None)
    justification: str
    evidence: list[str] = Field(
        default_factory=list,
        description="Exact resume snippets the verdict relied on; empty if unsatisfied",
    )

    @field_validator("evidence", mode="before")
    @classmethod
    def _coerce_evidence_to_list(cls, v):
        # The model (esp. with exactly one snippet) sometimes collapses the
        # list into a bare string, which fails Groq's own strict tool-call
        # schema check server-side -- we can't stop that rejection, but our
        # own recovery-path re-validation should still accept it rather than
        # repeatedly failing on the same systematic mistake.
        if isinstance(v, str):
            return [v] if v else []
        return v


class ExternalCorroborationVerdict(BaseModel):
    requirement: str = Field(description="The exact requirement text this verdict is for")
    corroborated: bool = Field(
        description=(
            "True only if the external evidence genuinely demonstrates real usage of this "
            "requirement -- a passing/incidental mention (e.g. the word appears in a file listing "
            "or an unrelated context) does NOT count. Same evidentiary bar as a resume claim."
        )
    )
    evidence: str = Field(default="", description="Exact quoted snippet supporting this; empty if not corroborated")
    justification: str = Field(default="")


class ExternalCorroborationResult(BaseModel):
    verdicts: list[ExternalCorroborationVerdict] = Field(default_factory=list)


class RequirementVerdict(RequirementVerdictCore):
    suggested_certification: str | None = Field(
        default=None,
        description=(
            "Only for unsatisfied requirements: a real, well-known, industry-recognized "
            "certification or course that would close this specific gap (e.g. 'Microsoft "
            "Certified: Azure Fundamentals (AZ-900)'). Null if satisfied, or if no widely "
            "recognized certification exists for this skill -- never invent one."
        ),
    )


class RubricResultCore(BaseModel):
    verdicts: list[RequirementVerdictCore] = Field(default_factory=list)


class RubricResult(BaseModel):
    verdicts: list[RequirementVerdict] = Field(default_factory=list)


class CertificationSuggestion(BaseModel):
    # Named `skill`, not `requirement` -- same openai/gpt-oss-20b field-naming
    # bug as WeightedSkill above (see its comment): the model reliably used
    # "skill" as the key here regardless of the schema's actual field name,
    # which Groq's own schema validation rejected outright on every call.
    skill: str = Field(description="The exact unsatisfied requirement/skill text this suggestion is for")
    suggested_certification: str | None = Field(
        default=None,
        description=(
            "A real, well-known, industry-recognized certification or course that would close "
            "this specific skill gap. Null if no widely recognized certification exists for this "
            "specific skill -- never invent one, and never suggest one for a different skill."
        ),
    )


class CertificationSuggestionList(BaseModel):
    suggestions: list[CertificationSuggestion] = Field(default_factory=list)


class ResumeSection(BaseModel):
    heading: str = Field(description="Section heading, e.g. 'Professional Summary', 'Skills', 'Experience'")
    lines: list[str] = Field(
        default_factory=list,
        description="Each bullet point or paragraph line in this section, in display order",
    )


class OptimizedResume(BaseModel):
    full_name: str | None = Field(default=None, description="Candidate's full name, if present in the resume")
    contact_line: str | None = Field(
        default=None, description="Single line combining email/phone/location, if present in the resume"
    )
    sections: list[ResumeSection] = Field(default_factory=list)


class FabricationCheck(BaseModel):
    fabricated_claims: list[str] = Field(
        default_factory=list,
        description=(
            "Skills, tools, technologies, certifications, job titles, or quantified achievements "
            "that appear in the OPTIMIZED text but are NOT genuinely present in the ORIGINAL resume "
            "text. Empty if the optimized text introduces nothing new."
        ),
    )


class ContactInfo(BaseModel):
    name: str | None = Field(default=None, description="The candidate's full name, if present on the resume")
    email: str | None = Field(default=None, description="The candidate's email address, if present on the resume")
    phone: str | None = Field(default=None, description="The candidate's phone number, if present on the resume")


# =======================
# Internal / non-LLM data shapes
# =======================


class DegreeInfo(BaseModel):
    all_degrees: list[str] = Field(default_factory=list)
    highest: str | None = None


class EligibilityResult(BaseModel):
    eligible: bool
    reasons: list[str] = Field(default_factory=list)


# =======================
# API response schemas
# =======================


class JobSeekerAnalysisResponse(BaseModel):
    eligibility: EligibilityResult
    resume_degree: DegreeInfo
    jd_degree: DegreeInfo
    resume_experience_years: int
    jd_experience_years: int
    overall_fit_score: float = 0.0
    skill_based_ats_score: float = 0.0
    requirement_verdicts: list[RequirementVerdict] = Field(default_factory=list)
    matched_requirements: list[str] = Field(default_factory=list)
    missing_requirements: list[str] = Field(default_factory=list)
    cover_letter: str | None = None
    optimized_resume: OptimizedResume | None = None


class CandidateResult(BaseModel):
    filename: str
    eligible: bool
    reasons: list[str] = Field(default_factory=list)
    experience_years: int = 0
    candidate_name: str | None = None  # LLM-extracted; only populated once round_reached == 3
    candidate_email: str | None = None
    candidate_phone: str | None = None
    overall_fit_score: float = 0.0
    skill_based_ats_score: float = 0.0  # only meaningful once round_reached == 3 (the LLM-verified rubric score)
    matched_requirements: list[str] = Field(default_factory=list)
    missing_requirements: list[str] = Field(default_factory=list)
    requirement_verdicts: list[RequirementVerdict] = Field(default_factory=list)
    provisional_score: float = 0.0  # round 1's dense-cosine screen
    skill_match_score: float = 0.0  # round 2's skill-vs-skill screen
    shortlisted: bool = False  # reached round 3 (full evidence-grounded review)
    round_reached: int = 0  # 0=ineligible, 1=cut after round 1, 2=cut after round 2, 3=fully reviewed


class RecruiterAnalysisResponse(BaseModel):
    job_role: str
    total_candidates: int
    ranked_candidates: list[CandidateResult] = Field(default_factory=list)


# =======================
# Async job status (live progress polling)
# =======================


class StageStatus(BaseModel):
    key: str
    label: str
    state: str  # pending | running | done


class CandidateStatus(BaseModel):
    filename: str
    state: str  # pending | running | done
    score: float | None = None
    phase: str = "pending"  # pending | round1 | round1_cut | round2 | round2_cut | round3 | done


class RoundCandidateSummary(BaseModel):
    filename: str
    eligible: bool
    reasons: list[str] = Field(default_factory=list)
    score: float = 0.0
    advancing: bool = False


class RoundSummary(BaseModel):
    round: int  # 1, 2, or 3
    label: str
    candidates: list[RoundCandidateSummary] = Field(default_factory=list)
    advancing_count: int = 0


class JobStatusResponse(BaseModel):
    job_id: str
    kind: str  # job_seeker | recruiter
    state: str  # queued | running | awaiting_approval | completed | failed
    stages: list[StageStatus] = Field(default_factory=list)
    candidates: list[CandidateStatus] = Field(default_factory=list)
    partial: dict = Field(default_factory=dict)
    verdicts: list[RequirementVerdict] = Field(default_factory=list)
    current_activity: str | None = None
    pending_approval: RoundSummary | None = None
    result: JobSeekerAnalysisResponse | RecruiterAnalysisResponse | None = None
    error: str | None = None
    report_id: str | None = None
